import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>From St. James to Santiago</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="hero" className="section section--hero">
        <div className="inner-wrapper inner-wrapper--hero">
          <h1 className="hero__title">From St. James to Santiago</h1>
        </div>
      </section>
      <section id="intro" className="section section--intro">
        <div className="inner-wrapper">
           
        </div>
      </section>
      <section id="stats" className="section section--stats">
        <div className="inner-wrapper">
          
        </div>
      </section>
    </>
  )
}